#!/bin/bash

# Define command-line arguments
NAMESPACE=$1
    if [ -z "$1" ]; then
        #NAMESPACE="kube-system"
        echo -e "Welcome!\nThis is Super plugin!\nPlease use: ./kubeplugin NAMESPACE\nThanks, have a great day!"
        exit
    fi

RESOURCE_TYPE=(pod node)

for RESOURCE_TYPE in "${RESOURCE_TYPE[@]}"
do
    # Retrieve resource usage statistics from Kubernetes
    kubectl top $RESOURCE_TYPE -n $NAMESPACE | tail -n +2 | while read line
        do
            # Extract CPU and memory usage from the output
            NAME=$(echo $line | awk '{print $1}')
            CPU=$(echo $line | awk '{print $2}')
            MEMORY=$(echo $line | awk '{print $3}')

            # Output the statistics to the console
            # "Resource, Namespace, Name, CPU, Memory"
            echo "$RESOURCE_TYPE, $NAMESPACE, $NAME, $CPU, $MEMORY"
        done
done